### ISSUE TITLE
Change text color for inactive tab

### ISSUE THREAD

**Issue by cipriancalinrad** [hoangthongbui/react-native-scrollable-tabstring#5]
Hello guys,
I want to change text color for inactive tabs. For inactive tabs i want to have text color blue, and for active text color white. How can i do that?

![image](https://user-images.githubusercontent.com/26228470/108205530-dcfd8000-712d-11eb-990d-8a27aed3b78a.png)
@Saad-Bashar @hoangthongbui

**Comment by cipriancalinrad** [comment]
i found

**Comment by Premangi** [comment]
@cipriancalinrad Can you please share the solution? It will be helpful. 
Thanks in advance! :)

**Comment by tinnakorn03** [comment]
I think this might help solve this problem.
[https://www.npmjs.com/package/react-native-scrollable-tabstring](url)
